# https://github.com/serverless-nextjs/serverless-next.js

meem-web:
  component: "@sls-next/serverless-component@3.7.0"
  inputs:
    runtime:
        defaultLambda: "nodejs16.x"
        apiLambda: "nodejs16.x"
        imageLambda: "nodejs16.x"
        roleArn: arn:aws:iam::376705315398:role/2gunlq-8y5tyot
    removeOldLambdaVersions: true
    timeout: 30
    memory: 1024
    useServerlessTraceTarget: true
    bucketName: ${env.S3_BUCKET_NAME}
    cloudfront:
      distributionId: ${env.CF_DISTRIBUTION_ID}
    name:
      defaultLambda: ${env.S3_BUCKET_NAME}-default
      apiLambda: ${env.S3_BUCKET_NAME}-api